[CMOB-1340] Feature: build UI
BakhvaJakeli/ChatApp pull request #1
Opened 2023-04-29 18:53 UTC by BakhvaJakeli

1. Removed Xib Files
2. Removed StoryBoard
3. Created custom Reusable textView, which becomes scrollable after 5 lines get added.
4. Created custom reusable textContainterView, which consists of custom textView and a send Button.
5. Created a custom re-usable chatView, which consists of custom textContainterView and tableView, which prints messages.
6. Added a custom switch button, which changes the mode of device (dark/light)
7. Created custom text bubbles for receivers and senders with bazaar path, which will get printed in tableviews.

This is the initial part of the UI for the whole project. I will later on add the logic and functionality, while making improvements for the UI where I can,

![Screenshot 2023-04-29 at 22 13 05](https://user-images.githubusercontent.com/85591231/235317963-d39a639a-c0a9-4708-a1a9-6f771819d132.png)
et functional, it can only be clicked) and it is possible to write text.
![Screenshot 2023-04-29 at 22 12 46](https://user-images.githubusercontent.com/85591231/235317984-875f3094-c361-4987-97a1-f680caa6b467.png)

2023-05-01 20:59 UTC, iLomidzeSpace requested changes
Good work!

There are mostly comments about style - making codebase better in terms of structure and readability.

"Please note that I have not repeated myself throughout."

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp.xcodeproj/project.pbxproj
> +		8FF84BFF29F94C3000A815E8 /* View */ = {
View Controller is not a view, it will be better to name folder as a "Controllers"

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp.xcodeproj/project.pbxproj
> +		8FF84C0129F94C5F00A815E8 /* Extension+UI */ = {
When having folder of extensions for native UIKit classes - just "Extensions" is OK

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp.xcodeproj/project.pbxproj
> +		8FF84C3229FBF14B00A815E8 /* Custom+UI */ = {
"Componenets" will be better name for this folder

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Assets.xcassets/Dark_Mode.imageset/Contents.json
> +      "filename" : "Group 103-2.pdf",
if it is pdf - make single scale

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Assets.xcassets/Vector.imageset/Contents.json
> +      "filename" : "Vector (2).pdf",
Vector is not very descriptive name.
P.S. start image naming from lowercase

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Constants/Constants.swift
> +struct Constants {
As I can see - this struct is not used anywhere - if so, delete it

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ChatView.swift
> +    // MARK: Text Field View
the name is self-explanatory and does not require // MARK: 

Try grouping Outlets with just 1 mark, like this:
```suggestion
    // MARK: - Outlets
```

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ChatView.swift
> +    // MARK: Chat Table View
```suggestion
```

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ChatView.swift
> +
Try adding init mark here:

```suggestion
    // MARK: - Init
```

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ChatView.swift
> +
The code will be much nicer if you write this private view builder functions in a private extension

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ChatView.swift
> +    private func addConstraints() {
for a number of lines point of view, your approach is nice, but when you have many components it will most definitely be a better approach to have separate functions for each component constraints

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ChatView.swift
> +        return 0
1 line code does not require return.
this is not an error or something, but this will be peatier. 
```suggestion
    0
```

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ChatView.swift
> +        return UITableViewCell()
same here, no extra lines are needed

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ReceiverChatBubbleVIew.swift
> +        let mainTextBubble = UIBezierPath(roundedRect: CGRect(x: 32,
Create Constants in this class extension - it will be much better

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ReceiverChatBubbleVIew.swift
> +                                          cornerRadius: 25)
also here and in general

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ReceiverChatBubbleVIew.swift
> +
```suggestion
```

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ReceiverChatBubbleVIew.swift
> +    let timeLabel = UILabel()
why do you need this labels?

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ScrollableTextField.swift
> +    var placeholder = "დაწერე შეტყობინება..."
Constants in this class also

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ScrollableTextField.swift
> +        return font
```suggestion
        font?.lineHeight ?? 0
```

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/ScrollableTextField.swift
> +    private func configurePlaceholderLabel() {
you can configure this label when you declare it.
and most certainly - separate setting constraints and building view into the separate functions

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/SenderChatBubbleView.swift
> +    let timeLabel = UILabel()
same question here + constants

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/SwitcherButton.swift
> +    func SwitcherIsPressed(_ button: SwitcherButton)
why do you need to pass button?

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/SwitcherButton.swift
> +        UIView.animate(withDuration: 0.5, animations: {
in general it is better approach to use [weak self] in completions to prevent retain cycles

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/TextFieldContainerView.swift
> +    var sendButton = UIButton(type: .system)
I guess it will be better to use closures to configure and initialize this button here.

also, make it private

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Custom+UI/TextFieldContainerView.swift
> +        layer.cornerRadius = 24
use constants

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Extension+UI/UIColor+Extensions.swift
> +extension UIColor {
please mind the code alignment

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/Extension+UI/UIImageView+Extensions.swift
> +
```suggestion
```

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/View/ViewController.swift
> +
user // MARK: - Outlets

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/View/ViewController.swift
> +final class ViewController: UIViewController {
maybe rename to something more close to its logic/screen dependant

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/View/ViewController.swift
> +        NSLayoutConstraint.activate([
separating different components constraints via marks good. would be better if you separate it in the different functions

P.S. dont forget about constants

2023-05-01 20:59 UTC, iLomidzeSpace commented on ChatApp/View/ViewControllerConstants.swift
> +extension ViewController {
can be better if constants will be in the same file and make it private extension

2023-05-02 10:52 UTC, BakhvaJakeli commented on ChatApp/Custom+UI/ReceiverChatBubbleVIew.swift
> +    let timeLabel = UILabel()
When I Will build Logic, the textBubble should have a label inside, as well as a timeLabel underneath, indicating when it was sent.

2023-05-02 11:03 UTC, BakhvaJakeli commented on ChatApp/Custom+UI/SwitcherButton.swift
> +    func SwitcherIsPressed(_ button: SwitcherButton)
To have the image change done, when clicked.

2023-05-02 11:04 UTC, BakhvaJakeli commented on ChatApp/Custom+UI/SwitcherButton.swift
> +        UIView.animate(withDuration: 0.5, animations: {
View animation doesn't cause retain cycles.

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Constants/Constants.swift
> +}
it would be better to make this struct of constants enum

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Constants/Constants.swift
> +}
same here

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Controlers/ChatViewController.swift
> +
setUpConstraints is very long functions, for readability purposes personally I prefer to decompose: setUpDividerViewConstraints(), setUpSwitcherButtonConstraints(), setUpFirstCharView(), setUpSecondChatView(), besides that marks would not be needed in the scope

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Controlers/ChatViewController.swift
> +        [dividerView, switcherButton, firstChatView, secondChatView].forEach { [weak self] theView in
theView is not a good name

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Controlers/ChatViewController.swift
> +            view.textField.textColor = .darkModeTextColor
I would decompose this as well

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Custom+UI/ChatView.swift
> +    // MARK: Outlets
are these outlets?

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Custom+UI/ReceiverChatBubbleVIew.swift
> +                                                      height: 20))
you can see apples guideline to how wrap code on lines
```suggestion
        let firstBubble = UIBezierPath(
            ovalIn: CGRect(
                x: mainTextBubble.bounds.minX - 5,
                y: mainTextBubble.bounds.maxY - 18,
                width: 20,
                height: 20
            )
        )
```

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Custom+UI/SenderChatBubbleView.swift
> +                                                       height: 10))
same here on line wrapping (its your choice but I think it would be good to get used to right code writing style from the beginning)

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Custom+UI/TextFieldContainerView.swift
> +        })
this should not happen in `addSubviews`

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Custom+UI/TextFieldContainerView.swift
> +            sendButton.heightAnchor.constraint(equalToConstant: TextFieldContainerViewConstants.buttonWidthAndHeight)
decompose this

2023-05-04 12:29 UTC, MariamOrmotsadze commented on ChatApp/Extensions/UIColor+Extensions.swift
> +                                           alpha: 1)
same here with line wrapping

2023-05-05 15:44 UTC, merged